//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinearXpert
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
        public static Entities context;
        public static Entities GetContext()
        {
            if (context == null)
                context = new Entities();
            return context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<GroupsOfTeacher> GroupsOfTeacher { get; set; }
        public virtual DbSet<Profiles> Profiles { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<QuestionsOfTest> QuestionsOfTest { get; set; }
        public virtual DbSet<ReferenceBook> ReferenceBook { get; set; }
        public virtual DbSet<Results> Results { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Tests> Tests { get; set; }
        public virtual DbSet<TypesOfAnswer> TypesOfAnswer { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
