//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinearXpert
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionsOfTest
    {
        public int Id_QuestionsOfTest { get; set; }
        public int id_Test { get; set; }
        public int id_Question { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual Tests Tests { get; set; }
    }
}
