//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinearXpert
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceBook
    {
        public int Id_Entrie { get; set; }
        public string topic_Entrie { get; set; }
        public string description_Entrie { get; set; }
        public byte[] image_Entrie { get; set; }
        public string link_Entrie { get; set; }
    }
}
